#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win32 all
      cd deploy
      7z a ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-win32-qt5

- job: win64_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win64 all
      cd deploy
      7z a ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-win64-qt5

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

- job: macOS_qt5
  pool:
    vmImage: "macOS-14"
  steps:
  - bash: |
      sh build.sh macOS all
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-macOS-qt5

- job: macOS_qt6
  pool:
    vmImage: "macOS-14"
  steps:
  - bash: |
      sh environment.sh qt6
      sh build.sh macOS all
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-macOS-qt6

#--------------------------------------------------------------------------------------------------
# iOS
#--------------------------------------------------------------------------------------------------

- job: iOS_qt5
  pool:
    vmImage: "macOS-14"
  steps:
  - bash: |
      sh build.sh iOS all
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-iOS-qt5

- job: iOS_qt6
  pool:
    vmImage: "macOS-14"
  steps:
  - bash: |
      sh environment.sh qt6
      sh build.sh iOS all
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-iOS-qt6

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

- job: linux32_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Sky i386/ubuntu:20.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Sky;
                                     apt-get update;
                                     apt-get -y install sudo curl zip git;
                                     sh build.sh linux all;
                                     cd deploy;
                                     zip -rq ../Sky.zip *"
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-linux32-qt5

- job: linux64_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      sh build.sh linux all
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-linux64-qt5

#--------------------------------------------------------------------------------------------------

- job: linux64_qt6
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      sh environment.sh qt6
      sh build.sh linux all
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-linux64-qt6

#--------------------------------------------------------------------------------------------------
# Android
#--------------------------------------------------------------------------------------------------

- job: android_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      sh build.sh android all
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-android-qt5

- job: android_qt6
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      sh environment.sh qt6
      sh build.sh android all
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-android-qt6
